# Standardization (Z-Score)

Standardization is a feature scaling technique that transforms numerical
features so that they have a mean approximately equal to 0 and a standard
deviation approximately equal to 1.

Formula:

Z = (x - μ) / σ


In [5]:
import numpy as np
ages = np.array([20,24,34,30,41,34])
mean = ages.sum()/len(ages)
print("Mean : ",mean)

std = np.std(ages)
print("Standard Deviation :" , std)

Mean :  30.5
Standard Deviation : 6.922186552431729


In [8]:
# z_scores = (ages - mean )/std
# here without using loop numpy allows us to operate array element one by one
z_scores = []

for age in ages:
    z = (age - mean) / std
    z_scores.append(z)


    
print("Z-score : ",z_scores)

Z-score :  [np.float64(-1.516861748880692), np.float64(-0.9390096540689998), np.float64(0.5056205829602307), np.float64(-0.07223151185146152), np.float64(1.516861748880692), np.float64(0.5056205829602307)]


In [9]:
print(np.mean(z_scores))

3.700743415417188e-17


In [10]:

print(ages)
print("Mean:", mean)
print("Standard Deviation:", std)
print("Z-score:", z_scores)

[20 24 34 30 41 34]
Mean: 30.5
Standard Deviation: 6.922186552431729
Z-score: [np.float64(-1.516861748880692), np.float64(-0.9390096540689998), np.float64(0.5056205829602307), np.float64(-0.07223151185146152), np.float64(1.516861748880692), np.float64(0.5056205829602307)]


In [11]:
print("Z-score:", np.round(z_scores, 2))

Z-score: [-1.52 -0.94  0.51 -0.07  1.52  0.51]


## Standardization using StandardScaler

Instead of calculating the mean, standard deviation, and Z-scores manually,
we can use Scikit-learn's `StandardScaler`.

It performs the same standardization process automatically.

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

scaler.fit(ages.reshape(-1, 1))

# This is important.
# fit() calculates and remembers:

# Meanokay 
# Standard deviation
# For your data, it learns approximately:

In [15]:
scaled_ages = scaler.transform(ages.reshape(-1, 1))

print(scaled_ages)

[[-1.51686175]
 [-0.93900965]
 [ 0.50562058]
 [-0.07223151]
 [ 1.51686175]
 [ 0.50562058]]


## Understanding `reshape(-1, 1)`

Scikit-learn expects input data in a **2D format**:

* Rows → samples/observations
* Columns → features

Our original data:

```python
ages = np.array([20, 24, 34, 30, 41, 34])
```

has the shape:

```python
ages.shape
```

Output:

```text
(6,)
```

This is a **1D array** containing 6 values.

To convert it into a 2D structure with 1 feature:

```python
ages.reshape(-1, 1)
```

Output:

```text
[[20]
 [24]
 [34]
 [30]
 [41]
 [34]]
```

Its shape becomes:

```text
(6, 1)
```

This means:

* `6` → 6 samples
* `1` → 1 feature

### What does `-1` mean?

In:

```python
ages.reshape(-1, 1)
```

`1` means **one column**.

`-1` tells NumPy to automatically calculate the required number of rows.

For 6 values:

```text
6 rows × 1 column
```

Therefore:

```text
(6, 1)
```

---

## `fit()`

`fit()` makes the scaler **learn the statistics from the data**.

```python
scaler.fit(ages.reshape(-1, 1))
```

For StandardScaler, it learns:

* Mean
* Standard deviation

For our data:

```text
Mean = 30.5
Standard deviation ≈ 6.922
```

The learned values can be viewed using:

```python
print(scaler.mean_)
print(scaler.scale_)
```

`fit()` does **not** return the scaled data.

### Remember:

> `fit()` = Learn from the data

---

## `transform()`

`transform()` uses the statistics learned during `fit()` to transform the data.

```python
scaled_ages = scaler.transform(ages.reshape(-1, 1))
```

It applies the Z-score formula:

$$
Z = \frac{x-\mu}{\sigma}
$$

For example:

```text
20 → -1.5169
24 → -0.9390
34 →  0.5056
30 → -0.0722
41 →  1.5169
34 →  0.5056
```

### Remember:

> `transform()` = Apply the learned transformation

---

## `fit_transform()`

`fit_transform()` combines both operations:

```python
scaled_ages = scaler.fit_transform(ages.reshape(-1, 1))
```

It performs:

```text
fit()
  ↓
Learn mean and standard deviation
  ↓
transform()
  ↓
Produce scaled data
```

So:

> `fit_transform()` = `fit()` + `transform()`

---

## Important ML Rule: Training and Testing Data

When working with machine learning, we normally use:

```python
X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)
```

We use `fit_transform()` on the **training data** because the scaler should learn the mean and standard deviation from the training data.

We use only `transform()` on the **testing data** because the test data should not be used to calculate those statistics.

This helps prevent **data leakage**.

### Quick Summary

| Method            | Purpose                            |
| ----------------- | ---------------------------------- |
| `reshape(-1, 1)`  | Converts 1D data into 2D format    |
| `fit()`           | Learns mean and standard deviation |
| `transform()`     | Applies the learned scaling        |
| `fit_transform()` | Learns and applies scaling         |


## Train-Test Scaling Example

In a real machine learning project, we should fit the scaler only on the training data.

The scaler learns the mean and standard deviation from the training data.

### Important Rule

Training data → `fit_transform()`

Testing data → `transform()`

We do not fit the scaler separately on the testing data because that would allow information from the test data to influence the preprocessing.

This helps prevent **data leakage**.

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample data
X = np.array([[20], [24], [34], [30], [41], [34]])

# Split data into training and testing sets
X_train, X_test = train_test_split(
    X,
    test_size=0.33,
    random_state=42
)

# Create the scaler
scaler = StandardScaler()

# Learn from training data and transform it
X_train_scaled = scaler.fit_transform(X_train)

# Use the same learned scaler to transform test data
X_test_scaled = scaler.transform(X_test)

print("Training data:")
print(X_train)

print("\nScaled training data:")
print(X_train_scaled)

print("\nTesting data:")
print(X_test)

print("\nScaled testing data:")
print(X_test_scaled)

Training data:
[[34]
 [34]
 [41]
 [30]]

Scaled training data:
[[-0.18935832]
 [-0.18935832]
 [ 1.57798601]
 [-1.19926937]]

Testing data:
[[20]
 [24]]

Scaled testing data:
[[-3.72404698]
 [-2.71413593]]


## Standardization Summary

Standardization transforms numerical features using the Z-score formula:

Z = (x - μ) / σ

After standardization:

- Mean is approximately 0
- Standard deviation is approximately 1
- Values are not restricted between 0 and 1

### Concepts Learned

1. Z-score
2. Mean and standard deviation
3. NumPy vectorized operations
4. `reshape(-1, 1)`
5. `StandardScaler`
6. `fit()`
7. `transform()`
8. `fit_transform()`
9. Train-test scaling
10. Data leakage

### Commonly Used With

Standardization is commonly useful for:

- KNN
- K-Means
- SVM
- Logistic Regression
- Linear Regression
- Neural Networks
- PCA

Tree-based algorithms generally do not require feature scaling.