# Min-Max Scaling (Normalization)

## 1. What is Min-Max Scaling?

Min-Max Scaling is a feature scaling technique used to transform numerical features into a fixed range, usually **0 to 1**.

It preserves the relative relationship between the original values while changing their scale.

### Example

Original values:

| Age |
| --: |
|  20 |
|  30 |
|  40 |
|  50 |
|  60 |

After Min-Max Scaling:

| Age | Scaled Age |
| --: | ---------: |
|  20 |       0.00 |
|  30 |       0.25 |
|  40 |       0.50 |
|  50 |       0.75 |
|  60 |       1.00 |

---

## 2. Why is Min-Max Scaling used?

Different features can have very different ranges.

For example:

* Age → 20–60
* Salary → 20,000–200,000
* Experience → 0–15

Features with different scales can affect some machine learning algorithms.

Min-Max Scaling transforms them into a common range:

* Age → 0–1
* Salary → 0–1
* Experience → 0–1

This makes the features comparable in scale.

---

## 3. Min-Max Scaling Formula

The standard formula is:

$$
X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}}
$$

Where:

* `X` = current value
* `X_min` = minimum value of the feature
* `X_max` = maximum value of the feature
* `X_scaled` = scaled value

---

## 4. Numerical Example

Suppose:

```text
Current Age = 40
Minimum Age = 20
Maximum Age = 60
```

Using the formula:

$$
X_{scaled} = \frac{40 - 20}{60 - 20}
$$

$$
= \frac{20}{40}
$$

$$
= 0.5
$$

Therefore:

```text
40 → 0.5
```

This means that 40 is halfway between the minimum value (20) and maximum value (60).

---

## 5. Important Point

Min-Max Scaling does **not** change the actual meaning of the data.

For example:

```text
20 years → 0.00
40 years → 0.50
60 years → 1.00
```

`0.50` does not mean 0.5 years.

It represents the position of 40 relative to the minimum and maximum values.

---

## 6. Advantages

* Converts features to a common scale.
* Usually produces values between 0 and 1.
* Preserves the relative relationships between values.
* Useful for algorithms that are sensitive to feature scale.
* Particularly useful when a bounded range is desired.

---

## 7. Disadvantage

Min-Max Scaling is **sensitive to outliers**.

Because the calculation uses the minimum and maximum values, an extreme value can change the range and compress most other values into a smaller portion of the 0–1 range.

---

## 8. Standardization vs Min-Max Scaling

| Standardization                  | Min-Max Scaling                                |
| -------------------------------- | ---------------------------------------------- |
| Uses mean and standard deviation | Uses minimum and maximum                       |
| Uses `StandardScaler`            | Uses `MinMaxScaler`                            |
| No fixed output range            | Usually produces 0–1                           |
| Can produce negative values      | Usually does not produce negative values       |
| Sensitive to outliers            | Highly sensitive to minimum and maximum values |

---

## 9. Python Implementation

Scikit-learn provides `MinMaxScaler` for Min-Max Scaling.

```python
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)
```

### Important

`fit()` learns the minimum and maximum values from the data.

`transform()` uses those learned values to scale the data.

`fit_transform()` performs both operations together.

---

## 10. Key Takeaway

**Min-Max Scaling transforms numerical features into a common range, usually 0 to 1, using the minimum and maximum values of the feature.**


In [2]:
import pandas as pd
df=pd.read_csv("../../data/minmax_scaling_data.csv")

In [3]:
df

,employee_id,age,salary,experience
0,101,22,25000,1
1,102,24,28000,2
2,103,26,31000,3
3,104,28,35000,4
4,105,30,40000,5
5,106,32,45000,6
6,107,25,30000,2
7,108,35,55000,8
8,109,27,33000,3
9,110,40,70000,12


In [5]:
df.head()

,employee_id,age,salary,experience
0,101,22,25000,1
1,102,24,28000,2
2,103,26,31000,3
3,104,28,35000,4
4,105,30,40000,5


In [6]:
df.describe()

,employee_id,age,salary,experience
count,30.000000,30.000000,30.000000,30.000000
mean,115.500000,35.833333,59366.666667,9.833333
std,8.803408,8.670534,26437.282104,6.654443
min,101.000000,22.000000,25000.000000,1.000000
25%,108.250000,28.250000,36500.000000,4.250000
50%,115.500000,35.500000,56500.000000,8.500000
75%,122.750000,42.750000,77250.000000,14.750000
max,130.000000,52.000000,125000.000000,24.000000


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  30 non-null     int64
 1   age          30 non-null     int64
 2   salary       30 non-null     int64
 3   experience   30 non-null     int64
dtypes: int64(4)
memory usage: 1.1 KB


In [8]:
features = df[["age", "salary", "experience"]]

In [9]:
features

,age,salary,experience
0,22,25000,1
1,24,28000,2
2,26,31000,3
3,28,35000,4
4,30,40000,5
5,32,45000,6
6,25,30000,2
7,35,55000,8
8,27,33000,3
9,40,70000,12


In [13]:
min_values = features.min()
max_values = features.max()
print(min_values)
print(max_values)

age              22
salary        25000
experience        1
dtype: int64
age               52
salary        125000
experience        24
dtype: int64


In [38]:
manual_scaled = (features - min_values) / (max_values - min_values)
manual_scaled

,age,salary,experience
0,0.000000,0.00,0.000000
1,0.066667,0.03,0.043478
2,0.133333,0.06,0.086957
3,0.200000,0.10,0.130435
4,0.266667,0.15,0.173913
5,0.333333,0.20,0.217391
6,0.100000,0.05,0.043478
7,0.433333,0.30,0.304348
8,0.166667,0.08,0.086957
9,0.600000,0.45,0.478261


In [39]:
df[["age_scaled", "salary_scaled", "experience_scaled"]] = manual_scaled
df

,employee_id,age,salary,experience,age_scaled,salary_scaled,experience_scaled
0,101,22,25000,1,0.000000,0.00,0.000000
1,102,24,28000,2,0.066667,0.03,0.043478
2,103,26,31000,3,0.133333,0.06,0.086957
3,104,28,35000,4,0.200000,0.10,0.130435
4,105,30,40000,5,0.266667,0.15,0.173913
5,106,32,45000,6,0.333333,0.20,0.217391
6,107,25,30000,2,0.100000,0.05,0.043478
7,108,35,55000,8,0.433333,0.30,0.304348
8,109,27,33000,3,0.166667,0.08,0.086957
9,110,40,70000,12,0.600000,0.45,0.478261


In [20]:
df.loc[df["employee_id"] == 105,
       ["age", "age_scaled",
        "salary", "salary_scaled",
        "experience", "experience_scaled"]]

# df.columns


,age,age_scaled,salary,salary_scaled,experience,experience_scaled
4,30,0.266667,40000,0.15,5,0.173913


<h1>Using the Scikit-learn</h1>

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler = MinMaxScaler()

In [24]:
features = df[["age", "salary" , "experience"]]

In [26]:
scaler.fit(features)

# fit()
#   ↓
# Find min & max
#   ↓
# Remember them inside scaler
# fit() learns the minimum and maximum values from each column.

MinMaxScaler()

In [27]:
scaler.data_max_

array([5.20e+01, 1.25e+05, 2.40e+01])

In [28]:
scaler.data_min_

array([2.2e+01, 2.5e+04, 1.0e+00])

In [41]:
sklearn_scaled = scaler.transform(features)

In [42]:
sklearn_scaled

array([[0.        , 0.        , 0.        ],
       [0.06666667, 0.03      , 0.04347826],
       [0.13333333, 0.06      , 0.08695652],
       [0.2       , 0.1       , 0.13043478],
       [0.26666667, 0.15      , 0.17391304],
       [0.33333333, 0.2       , 0.2173913 ],
       [0.1       , 0.05      , 0.04347826],
       [0.43333333, 0.3       , 0.30434783],
       [0.16666667, 0.08      , 0.08695652],
       [0.6       , 0.45      , 0.47826087],
       [0.03333333, 0.02      , 0.        ],
       [0.23333333, 0.13      , 0.17391304],
       [0.3       , 0.17      , 0.2173913 ],
       [0.4       , 0.25      , 0.30434783],
       [0.53333333, 0.4       , 0.39130435],
       [0.66666667, 0.5       , 0.56521739],
       [0.76666667, 0.6       , 0.69565217],
       [0.86666667, 0.7       , 0.82608696],
       [0.93333333, 0.85      , 0.91304348],
       [0.5       , 0.35      , 0.39130435],
       [0.36666667, 0.22      , 0.26086957],
       [0.46666667, 0.33      , 0.34782609],
       [0.

In [43]:
scaled_df = pd.DataFrame(sklearn_scaled, columns =["age_scaled", "salary_scaled", "experience_scaled"])
scaled_df

,age_scaled,salary_scaled,experience_scaled
0,0.000000,0.00,0.000000
1,0.066667,0.03,0.043478
2,0.133333,0.06,0.086957
3,0.200000,0.10,0.130435
4,0.266667,0.15,0.173913
5,0.333333,0.20,0.217391
6,0.100000,0.05,0.043478
7,0.433333,0.30,0.304348
8,0.166667,0.08,0.086957
9,0.600000,0.45,0.478261


In [44]:
df[["age_scaled", "salary_scaled", "experience_scaled"]] = scaled_df


In [45]:
df.head()

,employee_id,age,salary,experience,age_scaled,salary_scaled,experience_scaled
0,101,22,25000,1,0.000000,0.00,0.000000
1,102,24,28000,2,0.066667,0.03,0.043478
2,103,26,31000,3,0.133333,0.06,0.086957
3,104,28,35000,4,0.200000,0.10,0.130435
4,105,30,40000,5,0.266667,0.15,0.173913


In [47]:
df

,employee_id,age,salary,experience,age_scaled,salary_scaled,experience_scaled
0,101,22,25000,1,0.000000,0.00,0.000000
1,102,24,28000,2,0.066667,0.03,0.043478
2,103,26,31000,3,0.133333,0.06,0.086957
3,104,28,35000,4,0.200000,0.10,0.130435
4,105,30,40000,5,0.266667,0.15,0.173913
5,106,32,45000,6,0.333333,0.20,0.217391
6,107,25,30000,2,0.100000,0.05,0.043478
7,108,35,55000,8,0.433333,0.30,0.304348
8,109,27,33000,3,0.166667,0.08,0.086957
9,110,40,70000,12,0.600000,0.45,0.478261


In [48]:
import numpy as np

np.allclose(
    manual_scaled.values,
    sklearn_scaled
)

True